# ========== Name of the configuration ==========
name = LaboratorioDHGLogConfiguration

# Log files location
property.basePath = ${sys:logPath:-logs}

# ========== Console appender configuration ==========
appender.console.type = Console
appender.console.name = consoleLogger
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] %C (%F:%L): %msg%n

# ========== Default RollingFileAppender name, pattern, path and rollover policy ==========
appender.rolling.type = RollingFile
appender.rolling.name = fileLogger
appender.rolling.fileName = ${basePath}/aplicacion.log
appender.rolling.filePattern = ${basePath}/aplicacion-%d{yyyy-MM-dd}.gz
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] %C: %msg%n
appender.rolling.policies.type = Policies

# ========== Default RollingFileAppender rotation policy ==========
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 200MB
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 1

# Set file rotation in rounded time intervals
appender.rolling.policies.time.modulate = true

# Enable file deletion
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.delete.type = Delete
appender.rolling.strategy.delete.basePath = ${basePath}

# Maximum depth of managed files in the logs directory
appender.rolling.strategy.delete.maxDepth = 10

# Delete files not modified in 30 days or more
appender.rolling.strategy.delete.ifLastModified.type = IfLastModified
appender.rolling.strategy.delete.ifLastModified.age = 30d

# ========== Root logger level ==========
rootLogger.level = warn

# ========== Root logger referring to console appender ==========
rootLogger.appenderRef.stdout.ref = consoleLogger
rootLogger.appenderRef.rolling.ref = fileLogger

# ========== Sideralsoft commons packages logger ==========
logger.commons.name = com.sideralsoft.commons
logger.commons.level = debug
logger.commons.appenderRef.stdout.ref = consoleLogger
logger.commons.appenderRef.file.ref = fileLogger
logger.commons.additivity = false

# ========== Sideralsoft interface packages logger ==========
logger.interfaz.name = com.sideralsoft.interfaz
logger.interfaz.level = debug
logger.interfaz.appenderRef.stdout.ref = consoleLogger
logger.interfaz.appenderRef.file.ref = fileLogger
logger.interfaz.additivity = false

# ========== IndexController class logger ==========
logger.indexController.name = com.sideralsoft.interfaz.component.IndexController
logger.indexController.level = info
logger.indexController.appenderRef.stdout.ref = consoleLogger
logger.indexController.appenderRef.file.ref = fileLogger
logger.indexController.additivity = false